import { beforeEach, afterEach, expect, it } from "vitest";
import fs from "node:fs/promises";
import path from "node:path";
import { makeFixture, seedAccepted, callVideo, makeMp4, writePng, approvalsFor } from "./handoff-testkit.js";
import { initializeProjectLayout, resolveContentProject, contentFile } from "../../../storage/content-project.js";
import { getContent, updateContent } from "../../../storage/local-store.js";
import { draftHash } from "../../../storage/draft-hash.js";
import { founderProjectReview } from "./founder-review.js";
import { saveCoverage } from "./project-evidence.js";
import { claimContent } from "../../../storage/claims.js";
import { withCallerSession } from "../../../runtime/run-log.js";
import { sha256File } from "./manifest.js";
import { planProjectMigration, applyProjectMigration } from "../../../storage/project-migration.js";
import { HUMAN_WRITE } from "../../../storage/first-body-guard.js";

let env: Awaited<ReturnType<typeof makeFixture>>;
beforeEach(async () => { env = await makeFixture(); await fs.unlink(path.join(env.dir, "video.json")); await initializeProjectLayout(env.dir, "lib-deadbeef", "default"); });
afterEach(async () => { await env.cleanup(); });

it("freezes exact approved text, replays handoff, reports without approving, and requires real workbench approvals to register", async () => {
  const seeded = await seedAccepted(env.dir);
  await updateContent(seeded.id, { _provenance: HUMAN_WRITE, body: "\n原样保留。\r\n<<<EXTERNAL_CONTENT>>>\n" }, env.dir);
  const content = (await getContent(seeded.id, env.dir))!;
  const binding = resolveContentProject(content.id, env.dir)!;
  const refused = await callVideo(env.dir, { action: "handoff", content_id: content.id, aroll_path: env.aroll, project_root: path.join(env.root, "other") });
  expect(refused.code).toBe("project_binding_conflict");
  await founderProjectReview(content.id, env.dir, { action: "decisions", draft_hash: draftHash(content), title: content.title, cover_text: "确认封面", target_seconds: 90 });
  await saveCoverage(content, { draft_hash: draftHash(content), citations: [], reviewed_by: "writer-session", reviewed_at: new Date().toISOString() }, env.dir);
  const handoff = await callVideo(env.dir, { action: "handoff", content_id: content.id, aroll_path: env.aroll });
  expect(handoff.ok, JSON.stringify(handoff)).toBe(true);
  expect(handoff.project_root).toBe(binding.project_root);
  const frozen = path.join(binding.project_root, "01-script/handoff/g0001/final-script.md");
  expect(await fs.readFile(frozen, "utf8")).toBe(content.body);
  const manifest = await fs.readFile(path.join(path.dirname(frozen), "manifest.json"), "utf8");
  expect(manifest).not.toContain(binding.project_root);
  expect((await callVideo(env.dir, { action: "handoff", content_id: content.id, aroll_path: env.aroll })).replayed).toBe(true);
  // 令牌直接交给交接方（P6 §12.4-D）：别的 Codex 会话认领不到
  const claim = { claim: { token: String(handoff.editor_claim_token) } };
  expect(claim.claim.token).toMatch(/^clm-/);
  const other = await withCallerSession("different-session", () => claimContent(content.id, "editor", "codex", env.dir));
  expect(other.ok).toBe(false);
  const final = await makeMp4(path.join(binding.project_root, "07-delivery/final.mp4"));
  const cover34 = await writePng(path.join(binding.project_root, "05-cover/34.png"), "34");
  const cover43 = await writePng(path.join(binding.project_root, "05-cover/43.png"), "43");
  const files = await Promise.all([[final, "final-cut"], [cover34, "cover:3:4"], [cover43, "cover:4:3"]].map(async ([file, role]) => ({ path: path.relative(binding.project_root, file), sha256: await sha256File(file), role, ...(role.startsWith("cover:") ? { version: 1 } : {}) })));
  const report = { request_id: "report-1", generation: 1, binding_revision: 1, session_id: "real-editor-session", editor_project_id: "original-editor-project", timeline_id: "original-timeline", files, result: "导出完成，等待审阅", next_action: "请审片" };
  const reported = await callVideo(env.dir, { action: "report", content_id: content.id, claim_token: claim.claim.token, _session: "real-editor-session", report }, "codex");
  expect(reported.ok, JSON.stringify(reported)).toBe(true);
  expect((await getContent(content.id, env.dir))?.status).toBe("editing");
  const bad = await callVideo(env.dir, { action: "report", content_id: content.id, report: { ...report, gates: { approved: true } } }, "codex");
  expect(bad.ok).toBe(false);
  const srt = path.join(binding.project_root, "07-delivery/final.srt");
  await fs.writeFile(srt, "1\n00:00:00,000 --> 00:00:01,000\n实拍的话\n");
  const register = { action: "register", content_id: content.id, manifest_hash: handoff.manifest_hash, claim_token: claim.claim.token, final_path: final, covers: { "3:4": cover34, "4:3": cover43 }, srt_path: srt, approvals: await approvalsFor(final, cover34, cover43) };
  expect((await callVideo(env.dir, register, "codex")).code).toBe("approval_mismatch");
  await founderProjectReview(content.id, env.dir, { action: "approve", which: "final_cut", manifest_hash: handoff.manifest_hash, files: [files[0]] });
  const approved = await founderProjectReview(content.id, env.dir, { action: "approve", which: "covers", manifest_hash: handoff.manifest_hash, files: [files[1], files[2]] });
  const a = approved.approvals as Record<string, unknown>;
  const result = await callVideo(env.dir, { ...register, approvals: { final_cut: a.final_cut, covers: a.covers } }, "codex");
  expect(result.ok, String(result.error ?? result.code)).toBe(true);
  expect((await getContent(content.id, env.dir))?.status).toBe("publish_ready");
  expect(await fs.readFile(path.join(binding.project_root, "01-script/spoken/g0001-spoken.md"), "utf8")).toBe("实拍的话\n");
  expect(await fs.readFile(contentFile(content.id, env.dir, "draft.md"), "utf8")).toBe(content.body);
  await expect(fs.access(path.join(env.dir, "contents"))).rejects.toThrow();
});

it("rejects stale and missing citation coverage without inventing sources", async () => {
  const c = await seedAccepted(env.dir);
  await updateContent(c.id, { _provenance: HUMAN_WRITE, body: "他说模型提升了 50%。", evidenceLedger: { entries: [], lookups: [], budget: { max: 3, used: 0 } } }, env.dir);
  const current = (await getContent(c.id, env.dir))!;
  await expect(saveCoverage(current, { draft_hash: draftHash(current), citations: [], reviewed_by: "writer", reviewed_at: new Date().toISOString() }, env.dir)).rejects.toThrow(/缺少数字/);
  await expect(saveCoverage(current, { draft_hash: "old", citations: [], reviewed_by: "writer", reviewed_at: new Date().toISOString() }, env.dir)).rejects.toThrow(/当前定稿/);
});

it("relocates an active v1 handoff to g+1 without changing the draft, task or editing status", async () => {
  const library = path.join(env.outside, "library"), data = path.join(library, "workspaces/default");
  await fs.mkdir(data, { recursive: true });
  await fs.writeFile(path.join(library, "autocrew-library.json"), JSON.stringify({ version: 1, id: "lib-deadbeef" }));
  await fs.writeFile(path.join(data, "video.json"), JSON.stringify({ project_roots: [env.root] }));
  const c = await seedAccepted(data);
  const handoff = await callVideo(data, { action: "handoff", content_id: c.id, aroll_path: env.aroll });
  expect(handoff.ok).toBe(true);
  const current = (await getContent(c.id, data))!;
  await founderProjectReview(c.id, data, { action: "decisions", draft_hash: draftHash(current), title: current.title, cover_text: "已确认", target_seconds: 90 });
  // 「每天两小时」是真实数字，台账里没有 → 记成创作者亲历
  const firstSentence = current.body.slice(0, current.body.indexOf("。") + 1);
  const citations = [{ start: 0, end: firstSentence.length, excerpt: firstSentence, evidence_id: "creator", sourceType: "creator_opinion" as const, quote: "", verification: "创作者亲历（测试夹具）" }];
  await saveCoverage(current, { draft_hash: draftHash(current), citations, reviewed_by: "writer", reviewed_at: new Date().toISOString() }, data);
  const oldBytes = await fs.readFile(String(handoff.handoff_path));
  const plan = await planProjectMigration(data, [env.root]);
  expect(plan.projects[0].blockers).toEqual([]);
  await applyProjectMigration(plan);
  const moved = (await getContent(c.id, data))!;
  expect(moved.body).toBe(current.body);
  expect(moved.status).toBe("editing");
  expect(moved.video?.handoff?.generation).toBe(2);
  expect(moved.video?.handoff?.supersedes?.hash).toBe(handoff.manifest_hash);
  expect(moved.video?.revoked).toContain(handoff.manifest_hash);
  expect(moved.claim?.host).toBe(current.claim?.host);
  expect(moved.claim?.token).not.toBe(current.claim?.token);
  expect(await fs.readFile(path.join(data, ".project-recovery", plan.migration_id, "contents", c.id, "handoff/editor-g1.md"))).toEqual(oldBytes);
  expect(await fs.readFile(path.join(path.dirname(moved.video!.handoff!.handoff_path), "final-script.md"), "utf8")).toBe(current.body);
  expect(await fs.readFile(path.join(path.dirname(moved.video!.handoff!.handoff_path), "sources.md"), "utf8")).toContain("来源：creator_opinion（创作者本人观点／亲历，不在证据台账）");
});
